### Get all Recipes
GET http://localhost:8080/api/recipes

### Get Recipes by Filter parameters
GET http://localhost:8080/api/recipes?categories=vegan&preparationTime=16

### Get single Recipe by ID
GET http://localhost:8080/api/recipes/6467d38aa4725c2a87bb5208

### Get single non-existent Recipe
GET http://localhost:8080/api/recipes/643185e3187bd08e12d12345

### Get Recipes by Search parameter
GET http://localhost:8080/api/recipes/search?searchPhrase=banana

### Create new Recipe
POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "Some name here",
  "imageURL": "Some image URL",
  "ingredients": [
    {
      "name": "egg",
      "quantity": "1"
    },
    {
      "name": "bread",
      "quantity": "2"
    }
  ],
  "categories": [
    "meat",
    "rice"
  ],
  "types": [
    "Breakfast",
    "Snack"
  ],
  "steps": [
    "1. Qwerty prepare the ingredients",
    "2. Drop salt and pepper"
  ],
  "preparationTime": 20
}

### Update existing Recipe
PUT http://localhost:8080/api/recipes/644806cf1af8e6781cd12345
Content-Type: application/json

{
  "name": "HEHEHEHE",
  "imageURL": "Some image URL",
  "ingredients": [
    {
      "name": "egg",
      "quantity": "1"
    }
  ],
  "categories": [
    "meat",
    "rice"
  ],
  "types": [
    "Breakfast",
    "Snack"
  ],
  "steps": [
    "1. Qwerty prepare the ingredients",
    "2. Drop salt and pepper"
  ],
  "preparationTime": 20
}

### Delete by ID
DELETE http://localhost:8080/api/recipes/644806cf1af8e6781cd05025

### Log in as user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "lavoRka",
  "password": "123secretpassword"
}

### Register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testUser",
  "email": "testUser@gmail.com",
  "password": "testUser"
}